apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: deployment
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: apiinvillia
    spec:
      containers:
      - name: apiinvillia
        image: API_IMAGE_NAME
        ports:
          - containerPort: 8000
        env:
          - name: DB_NAME
            value: invillia
          - name: DB_HOST
            value: cloudsql:3306
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: cloudsql-db-credentials
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cloudsql-db-credentials
                key: password
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials